### ISSUE TITLE
ios无法调起微信

### ISSUE THREAD

**Issue by hbinyooo** [Hector-Chong/expo-native-wechat#10]
请问sendAuthRequest在ios端没有调起微信如何解决，谢谢。
■环境
IOS16.0，EXPO48.0.21，微信版本8.0.48

■现象
已按照指导信息，正确配置app.json。
安卓可以正常调起微信并成功登录以及获取用户信息。
IOS无法启动微信，也没有回调信息。
const data = await sendAuthRequest();

ios已正确配置app的Universal Links,并在手机上测试过。

调试了一下是这里没有进来：
<img width="765" alt="image" src="https://github.com/user-attachments/assets/7352369d-179e-4731-b014-cc3439010b4c">
<img width="180" alt="image" src="https://github.com/user-attachments/assets/3337d6c9-bfe1-48f4-9924-5067d6380a1c">

**Comment by hbinyooo** [comment]
找到原因了，ios的话需要在注册时传入universalLink, 如下：
registerApp({
    appid: 'wx96b2px111ebe9b7b',
    universalLink: 'https://hector.im/',
})

**Comment by 616151371** [comment]
universalLink要记得带协议，刚没带协议查了好久
