### ISSUE TITLE
sendAuthRequest 方法一直在pending状态

### ISSUE THREAD

**Issue by trevorHsu** [Hector-Chong/expo-native-wechat#15]
作者你好，很感谢你的开源。
我在使用过程中遇到一些问题，希望能够帮忙看一看~

环境：
"expo": "~51.0.8"
"expo-application": "^5.9.1"
"react-native":  "0.74.2"

项目基于Ignite生成的脚手架进行开发

问题：
调用 sendAuthRequest 方法后，微信界面会弹出，接着会迅速回到我自己的APP，
然后 sendAuthRequest 方法就一直在pending状态了

**Comment by Hector-Chong** [comment]
如果为 Android 端检查是否配置 Activity；如果为 iOS 端，请检查是否配置了 universalLink

**Comment by trevorHsu** [comment]
> 检查下 App.json 是否配置了 universalUrl 相关信息。

目前是在安卓端开发及测试，应该不需要加这个字段的。

除了以上的问题，还发现在通过expo云打包时，会出现这个报错提示，导致编译失败：

**Comment by trevorHsu** [comment]
发现源码中此处缺少引入依赖 Intent

**Comment by Hector-Chong** [comment]
已修复，谢谢反馈。
不过似乎 NPM 登录有问题，我晚点再发布更新。

335116d14d9f8dc5fb4ec36aa3f82668402ce36f

**Comment by Hector-Chong** [comment]
已发布 NPM 更新。

**Comment by trevorHsu** [comment]
刚刚更新了一下包，看到源码里还是没有修复。
而且在开发环境下，是没有报错的；正式打包的时候才会报这个错误。
开发环境下，调起微信后，没有响应微信的回调；是不是因为在开发环境下，没有插入这段menifest的配置呢？

> 发现源码中app.plugin.js，此处缺少对 Intent 的引入依赖 <img alt="bbbbbbb" width="734" src="https://private-user-images.githubusercontent.com/24761914/365984788-6d774cd9-0781-4033-a5f3-28b126505569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDM1MjcsIm5iZiI6MTcyNjA0MzIyNywicGF0aCI6Ii8yNDc2MTkxNC8zNjU5ODQ3ODgtNmQ3NzRjZDktMDc4MS00MDMzLWE1ZjMtMjhiMTI2NTA1NTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA4MjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YmVmYzYwOTYxYTY2MWE3YzZhYTg5YWE0NTkwODM4NjJmZDIxYjRkNTg2MzFiNGJkYzFjMzkwZDc1NTQzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9lI4xbhv4KZ37DhxqvT1RoRs0tUBF9VAyGgkAFi5XzM">

**Comment by Hector-Chong** [comment]
似乎昨天发布的包有问题，刚重新发布了版本。

<img width="1482" alt="image" src="https://github.com/user-attachments/assets/f0c6380e-1af6-4706-90ed-2dc4d20031e6">
