### ISSUE TITLE
Error: Cannot find native module 'ExpoNativeWechat'

### ISSUE THREAD

**Issue by laoer536** [Hector-Chong/expo-native-wechat#18]
使用yarn安装并按照文档配置了，但是报错：
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/94fbd618-9df6-4f44-8e88-add75aa374ed">
但是代码并没有报错
<img width="623" alt="image" src="https://github.com/user-attachments/assets/af83af59-1573-447d-a54f-d7bfe254f13a">
可以解答一下吗？谢谢

**Comment by Hector-Chong** [comment]
目前的 Expo SDK 版本是？

**Comment by Hector-Chong** [comment]
https://github.com/Hector-Chong/expo-native-wechat/pull/19

**Comment by laoer536** [comment]
> #19
> 
> 请尝试使用 0.2.0 版本。

还是存在这个问题🥹

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/1b9156cd-7dbd-4a7e-9b4f-96fc098bdb59">

另外就是加了之后 这个页面就显示
Route "./task-detail.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]

但实际上 我的页面是正确书写的，没加入expo-native-wechat之前是正常显示的。

求解答，谢谢🫶🏼

**Comment by laoer536** [comment]
> #19
> 
> 请尝试使用 0.2.0 版本。

另外还有一个问题就是 按照文档的描述，我的
<img width="496" alt="image" src="https://github.com/user-attachments/assets/83bd4460-ee8b-4470-8c13-a62be343471f">

scheme会整个替换写成"scheme": [appid], 这样会不会对原来的deepLink的跳转照成影响，根据https://docs.expo.dev/linking/into-your-app/的描述，我的app deepLink照成影响，因为直接替换掉了，如果有影响是否可以改成这种配置方式：
<img width="454" alt="image" src="https://github.com/user-attachments/assets/65c3ffb9-e34b-4795-addf-d52ad523454b">

**Comment by Hector-Chong** [comment]
> > #19
> > 请尝试使用 0.2.0 版本。
> 
> 还是存在这个问题🥹
> 
> <img alt="image" width="1148" src="https://private-user-images.githubusercontent.com/58387049/393521152-1b9156cd-7dbd-4a7e-9b4f-96fc098bdb59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTA0MjYsIm5iZiI6MTczMzcxMDEyNiwicGF0aCI6Ii81ODM4NzA0OS8zOTM1MjExNTItMWI5MTU2Y2QtN2RiZC00YTdlLTliNGYtOTZmYzA5OGJkYjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAyMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlY2M2MjcwMmVkM2I5YzBjZjk2ZmI0OTlhMGI4YWViMWNhZDFjZjcwMGI2YTg2ZmE5NzdiMGQ1N2RmY2E3YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YoPqIgwJa7ao8ecgNjcP0kB8k4AVU1-wUdBWFPAG3Fo">
> 另外就是加了之后 这个页面就显示 Route "./task-detail.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
> 
> 但实际上 我的页面是正确书写的，没加入expo-native-wechat之前是正常显示的。
> 
> 求解答，谢谢🫶🏼

是否尝试清空并重新构建了呢？

**Comment by Hector-Chong** [comment]
> > #19
> > 请尝试使用 0.2.0 版本。
> 
> 另外还有一个问题就是 按照文档的描述，我的 <img alt="image" width="496" src="https://private-user-images.githubusercontent.com/58387049/393521409-83bd4460-ee8b-4470-8c13-a62be343471f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTA0MjYsIm5iZiI6MTczMzcxMDEyNiwicGF0aCI6Ii81ODM4NzA0OS8zOTM1MjE0MDktODNiZDQ0NjAtZWU4Yi00NDcwLThjMTMtYTYyYmUzNDM0NzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAyMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTVjNWM4YjZiMjAwYzUwNjAyYTBiMDJiY2Q1OTAxMzNkZWU4ZDVhMGRkMzUwNDg1YzljMjgwNmU0NTdjZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.coaSB8crKeZYqiOzPEt85KZUSd0qjx4EEA4-HZP1Juw">
> 
> scheme会整个替换写成"scheme": [appid], 这样会不会对原来的deepLink的跳转照成影响，根据的[expo](https://docs.expo.dev/linking/into-your-app/)对`scheme`描述，我的app deepLink照成影响，因为直接替换掉了，如果有影响是否可以改成这种配置方式： <img alt="image" width="454" src="https://private-user-images.githubusercontent.com/58387049/393521787-65c3ffb9-e34b-4795-addf-d52ad523454b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTA0MjYsIm5iZiI6MTczMzcxMDEyNiwicGF0aCI6Ii81ODM4NzA0OS8zOTM1MjE3ODctNjVjM2ZmYjktZTM0Yi00Nzk1LWFkZGYtZDUyYWQ1MjM0NTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAyMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNjMzNGFlNzZmMGI2NjhjMWZkMzFkMzUyZTdlYmE0MmUzMmFiY2MyNWYwODNiNDQ0NDc4NzYyOWExMTE3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a2jhbcFZ2ReYmXySD3AKDjq9N9kSoxmBcV0wgN95Bis">

我最初也想这样设计的，但是微信那边必须要 scheme 为你的 App ID 同时 Expo 并没有提供其他的拓展 Scheme 方案。

**Comment by Hector-Chong** [comment]
deepLink 按照微信平台上配置。

**Comment by laoer536** [comment]
> deepLink 按照微信平台上配置。
谢谢

**Comment by 616151371** [comment]
0.2.0版本，我也出现这个错误了，解决方法是删除.gradle重新构建吗
