### ISSUE TITLE
expo-native-wechat支付没有回调

### ISSUE THREAD

**Issue by 418442040** [Hector-Chong/expo-native-wechat#3]
requestPayment方法不管成功还是失败都没有任何回调,代码如下:
  requestPayment({
                  partnerId: red.partnerid,
                  prepayId: red.prepayid,
                  nonceStr: red.noncestr,
                  timeStamp: red.timestamp.toString(),
                  sign: red.sign,
                })
                  .then((res) => {
                    console.log(res);
                  })
                  .catch((err) => {
                    console.log(err);
                  });

**Comment by Hector-Chong** [comment]
是否成功跳转到微信了？

**Comment by Hector-Chong** [comment]
很抱歉，之前遗漏了 Queries Schemas 的配置项，请尝试此操作。

https://native-wechat.hector.im/guide/configuration-expo.html

**Comment by 418442040** [comment]
> 很抱歉，之前遗漏了 Queries Schemas 的配置项，请尝试此操作。
> 
> https://native-wechat.hector.im/guide/configuration-expo.html

您好,你说的漏掉的可能是ios的配置,我指的是android不回调,并且我已经配置了 "scheme": ["wx123456nxabcdefg"]和"plugins": ["expo-native-wechat"],

**Comment by 418442040** [comment]
> 是否成功跳转到微信了？

有成功跳转到微信

**Comment by Hector-Chong** [comment]
已发布更新尝试修复，请再试一次。

**Comment by 418442040** [comment]
> 已发布更新尝试修复，请再试一次。

我尝试更新了一下,依然没有回调,不知您自己测试是否有回调?

**Comment by Hector-Chong** [comment]
由于我暂时没有支付的测试用例，您是否尝试过 Prebuild 工程了呢？

**Comment by Hector-Chong** [comment]
非常抱歉，我已发布了更新，请重试一下。

**Comment by lsp27** [comment]
支付还是不行哎，都没有跳转到微信
