### ISSUE TITLE
expo-native-wechat登录没有回调

### ISSUE THREAD

**Issue by foreverzhuo** [Hector-Chong/expo-native-wechat#4]
感谢时间。请问sendAuthRequest没有回调成功如何解决，谢谢。
■环境
Android14，Expo50.0.17 

■现象
已按照指导信息，正确配置app.json。
可以正常启动微信，授权成功会正常返回程序。但是没有返回任何对象。
下面代码没有回调成功，不输出任何错误且不返回代码data。xxx也没有正常输出。
```  
const data = await sendAuthRequest({ scope: 'snsapi_userinfo' });
console.log(data);
console.long("xxx")
```

**Comment by Hector-Chong** [comment]
请问是否重新 Prebuild 过工程了？

**Comment by Hector-Chong** [comment]
非常感谢你的反馈，我已发布更新，请麻烦重试一下。

**Comment by foreverzhuo** [comment]
> 非常感谢你的反馈，我已发布更新，请麻烦重试一下。

@Hector-Chong 
感谢大佬深夜更新，好用了。感谢，敬礼！
