### ISSUE TITLE
安卓 shareImage 无法正常拉起微信

### ISSUE THREAD

**Issue by buildnewapp** [Hector-Chong/expo-native-wechat#6]
"expo-native-wechat": "^0.1.4",
"react": "18.2.0",
"react-native": "0.73.6",
"expo": "~50.0.19",

iOS可以正常图片分享

**Comment by buildnewapp** [comment]
安卓源文件 没有 分享图片的方法：
https://github.com/Hector-Chong/expo-native-wechat/blob/main/android/src/main/java/expo/modules/nativewechat/ExpoNativeWechatModule.kt

是不是 不小心删了？麻烦看下

**Comment by buildnewapp** [comment]
修改代码：
/node_modules/expo-native-wechat/android/src/main/java/expo/modules/nativewechat/ExpoNativeWechatModule.kt

`
Function("shareImage") { params: ShareImageParams ->
      val src = params.src
      val scene = params.scene

      ExpoNativeWechatUtils.downloadFileAsBitmap(src, object : DownloadBitmapCallback {
          override fun onFailure(call: Call, e: IOException) {
            this@ExpoNativeWechatModule.sendEvent(
              "ResponseData", bundleOf(
                "id" to params.id,
                "success" to false,
                "message" to e.localizedMessage
              )
            )
          }

          override fun onResponse(bitmap: Bitmap) {
            val imgObj = WXImageObject(bitmap)
            val msg = WXMediaMessage()
            msg.mediaObject = imgObj

            bitmap?.let {
              msg.thumbData = ExpoNativeWechatUtils.bmpToByteArray(bitmap, 32, true)
            }

            val req = SendMessageToWX.Req()
            req.message = msg
            req.scene = scene

            sendEvent(
              "ResponseData", bundleOf(
                "id" to params.id,
                "success" to wxApi?.sendReq(req)
              )
            )

          }
      })

    }
`

**Comment by Hector-Chong** [comment]
很抱歉，我检查了代码是我的问题。由于我最近外出，这边网络很差，我会在周二处理。

**Comment by Hector-Chong** [comment]
0.1.5 has resolved this issue.
